---
name: Linting
on:
  push:
    branches-ignore: [ 'dependabot/**' ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Prettier Lint
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Setup Node
        uses: actions/setup-node@v1.4.6
        with:
          node-version: '14'
      - name: Install packages
        run: yarn install
      - name: Run lint
        run: yarn lint
