---
name: Linting
on:
  push:
    branches-ignore: [ 'dependabot/**' ]

jobs:
  lint:
    name: Prettier Lint
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install packages
        run: yarn install
      - name: Run lint
        run: yarn lint
