---
name: Code Linting
on:
  push:
    branches-ignore: [ 'dependabot/**' ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: TypeScript/JavaScript Lint - Prettier
    runs-on: [ubuntu-20.04, macos-11]
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Setup Node
        uses: actions/setup-node@1.4.6
        with:
          node-version: '14'
      - name: Install packages
        run: yarn install
      - name: Run tests
        run: yarn test
